//This code was autogenerated by ESP Mango code generator V1.2 for "sketch_espmango" sketch at: 25-08-2024 22:20:24
//ESP Mango code generator was created by Julian D. Medina --- JulianDM1995@gmail.com - 2020 

//==================================================================================================================================
//------------------------------------------------------| Connection events |-------------------------------------------------------
//==================================================================================================================================

//-----------------------------------------------------| On client connection |-----------------------------------------------------

void onClientConnection(uint8_t clientNum, uint8_t * payload) {
	if (FrontendToBackendDebug) { //For debugging purposes only. Remove if you want.
		IPAddress ip = websockets.remoteIP(clientNum);
		Serial.printf("[%u] Connected from %d.%d.%d.%d url: \" %s \"\n", clientNum, ip[0], ip[1], ip[2], ip[3], payload);
	}

	//Write your own code for "On client connection" here. Code inside this comments will not overwrite. DON'T EDIT OR REMOVE THIS COMMENTS. 	Code: occcabcdef



	//End of your own code. 	Code: occcabcdef

}

//---------------------------------------------------| On client disconnection |----------------------------------------------------

void onClientDisconnection(uint8_t clientNum) {
	if (FrontendToBackendDebug) Serial.printf("[%u] Disconnected!\n", clientNum);

	//Write your own code for "On client disconnection" here. Code inside this comments will not overwrite. DON'T EDIT OR REMOVE THIS COMMENTS. 	Code: ocdcabcdef



	//End of your own code. 	Code: ocdcabcdef

}

